### ISSUE TITLE
Issue in modification of split.jl file

### ISSUE THREAD

**Issue by bgpantojar** [NumSoftware/FemMesh#1]
Dear,

I need to use the function "generate_joints" located in file split.jl. I had to do a little modification because I need that joints to be generated only between different materials and don't between each solid element (ex. A discretized material in various elements currently are glued by joints and this isn't desired).

The modification was made in the lines 57 to 59 of attached image in file split.jl. The construction of the Tuple "face_pairs" is now conditioned by if the tags of the faces, given in the creation of blocks, are different.

![captura de tela de 2018-12-13 13-20-22](https://user-images.githubusercontent.com/35929939/49958878-1563fc80-feda-11e8-83f8-9136b2a72ec6.png)

I hopped that it is gonna be working but it didn't. In the mesh generation the program give a warning that can be seen in the image attached ("Warning: reorder!: Reordering nodes failed! Check for overlapping cells or non used points.").

![captura de tela de 2018-12-13 13-26-32](https://user-images.githubusercontent.com/35929939/49959236-0b8ec900-fedb-11e8-9376-b6461146fc0c.png)

As result, in the final analysis some elements of the structure were detached as can be seen in the images.

![captura de tela de 2018-12-13 13-29-51](https://user-images.githubusercontent.com/35929939/49959404-73451400-fedb-11e8-9ff6-b1805c6a9466.png)

![captura de tela de 2018-12-13 13-30-07](https://user-images.githubusercontent.com/35929939/49959419-7d671280-fedb-11e8-942d-d27f099433b1.png)

![captura de tela de 2018-12-13 13-30-27](https://user-images.githubusercontent.com/35929939/49959430-8526b700-fedb-11e8-970c-8baf064e2f2f.png)

I am trying to solve it but without success. Have you any idea that can work?

Thanks,

**Comment by RaulDurand** [comment]
The generation of joints between cells with different tags would be a very nice feature! 
I don't think this will be an easy task though. Notice that all points where already replicated for all solid cells (lines 33-40). Thus, joints everywhere are needed to keep cells linked. This procedure is the easiest to generate joints between all cells but not to generate joints at arbitrary locations as you desire.

I believe that it is better to create a new function for this. This new function could replicate some points only at material boundaries and later link them by joint cells. Some data structure would be needed to track these new points and cells. Make a sketch of a simple mesh on a piece of paper and check which points would need to be replicated and which not. I think that a simple and beautiful algorithm is possible.

Good luck!

PS. Also check whether a warning about nodal numbering appears (which was your case). This usually happens when we get an invalid mesh (mesh with overlapping cells or disconnected parts).
